version: '3'
services:
    ofrontend:
        build: 
            context: .
            dockerfile: Dockerfile.optimized
        stdin_open: true  #using for using command line
        tty: true
networks: 
  default: 
    external: 
      name: external-example
        
            
        
    
#  docker compose up --remove-orphans
# docker container run --rm --name hello -it hello
# https://stackoverflow.com/questions/66544508/golang-infinite-for-loop-problem-with-docker-run
# docker-compose run frontend
# docker-compose up --build -d --remove-orphans
# docker-compose -f docker-compose-optimized.yml up --build -d --remove-orphans