version: '3'
services:
  rest_normal:
    build: 
          context: .
          dockerfile: Dockerfile # uses Dockerfile in root dir to build the image

    ports:
      - target: 8080
        published: 8080
networks: 
  default: 
    external: 
      name: external-example



# docker-compose -f docker-compose.yml up

# frontend_default